// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxuoyililgjdscksyhiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dW95aWxpbGdqZHNja3N5aGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTU1NjIsImV4cCI6MjA1OTUzMTU2Mn0.JTmoRYIGu63IgkLnQsTbepubfUFLdHRfEAc_EPo7vYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);